name: 'Luacheck Action'
author: 'Jayrgo'

branding:
  icon: 'moon'
  color: 'blue'

inputs:
  files:
    description: 'List of files, directories and rockspecs to check.'
    default: '.'
    required: false
  config:
    description: 'Path to configuration file.'
    default: '.luacheckrc'
    required: false
  arguments:
    description: 'Arguments passed to luacheck.'
    default: ''
    required: false

runs:
  using: 'composite'
  steps:
    - name: Install LuaRocks
      run: sudo apt-get install luarocks -q
      shell: bash
    - name: Install Luacheck
      run: luarocks install --local luacheck
      shell: bash
    - name: Luacheck
      run: /home/runner/.luarocks/bin/luacheck --config ${{ inputs.config }} ${{ inputs.arguments }} ${{ inputs.files }}
      shell: bash
